<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<meta name="description" content="Mediamatiker EFZ, Bildungszentrum Zürichsee, Horgen">
<meta name="author" content="daniel.garavaldi@bzz.ch">
<!-- Bootstrap -->
<?php
//require_once(__DIR__ . '/../lib/Navigation.php');
//$nav = new Navigation();
//echo $nav->getSiteTitle();
//$path = "../../../../../";
$path = "./";
?>
<link href=<?=$path. "inc/vendor/bootstrap/css/bootstrap.css" ?> rel="stylesheet">
<link href=<?=$path. "inc/vendor/bootstrap/css/bootstrap-theme.css" ?> rel="stylesheet">
<link href=<?=$path. "inc/vendor/bootstrap/css/ie10-viewport-bug-workaround.css" ?> rel="stylesheet">
<script type="text/javascript" src=<?=$path. "inc/vendor/jquery/jquery-3.2.1.js" ?>></script>
<script>window.jQuery || document.write('<script src=<?=$path. "inc/vendor/bootstrap/js/jquery-2.2.2.min.js" ?>><\/script>')</script>
<script type="text/javascript" src=<?=$path. "inc/vendor/bootstrap/js/bootstrap.min.js" ?>></script>
<link href=<?=$path. "inc/vendor/highlight/css/highlight.agate.css" ?> media="screen" rel="stylesheet">
<script type="text/javascript" src=<?=$path. "inc/vendor/highlight/js/highlight.pack.js" ?>></script>
<script>hljs.initHighlightingOnLoad();</script>
<!-- Custom styles for this template -->
<link href=<?=$path. "inc/theme.css" ?> rel="stylesheet">
<!-- Custom scripts (JavaScripts) for this template -->
<script type="text/javascript" src=<?=$path. "inc/script/ui.js" ?>></script>
<script type="application/javascript"
        src=<?=$path. "inc/script/handlebars-v4.0.11.js" ?>></script>

<!--<script type="application/javascript"-->
<!--        src="inc/script/swap.js"></script>-->
