<footer class="footer">
    <div class="container">
        <p style="border-top: 1px solid black; margin-top: 15px;">
            <small>&copy; 2010-<?php date_default_timezone_set("Europe/Zurich");
                echo date("Y"); ?> Bildungszentrum Zürichsee, Horgen - Disclaimer: Nur BZZ-intern zu gebrauchen!
                Fachlehrer: <a href="mailto:daniel.garavaldi@bzz.ch">Daniel Garavaldi</a>
            </small>
        </p>
    </div>
</footer>